school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('timetable/', include('timetable.urls')),
    path('admin/', admin.site.urls),
]

school/timetable/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'timetable'
urlpatterns = [
    # path('', views.my_login, name='index'),
    path('login', auth_views.login, {'template_name': 'timetable/login.html'}, name='login'),
    path('login', auth_views.logout, {'template_name': 'timetable/login.html'}, name='logout'),
    path('home', views.home_page, name='home'),
    path('teacher', views.teacher_index, name='t_page'),
    path('teacher/register', views.registration, name='regis'),
    path('teacher/register/student/', views.StudentRegisterView.as_view(), name='s_signup'),
    path('teacher/register/teacher/', views.TeacherRegisterView.as_view(), name='t_signup'),
    path('teacher/groups', views.new_group, name='ngr'),
    path('teacher/communicate', views.new_communicate, name='ncom'),
    path('teacher/my_profile', views.person_profile, name='t_profile'),
    path('<int:id>/', views.group_participants, name='detail'),
    path('teacher/my_groups', views.teacher_groups, name='tgr'),
    path('teacher/new_participant', views.new_participant, name='new_part'),
    path('teacher/remove_participant', views.remove_participant, name='rm_part'),
    path('student', views.student_index, name='s_page'),
    path('student/my_groups', views.student_groups, name='s_groups'),
    path('student/my_profile', views.person_profile, name='s_profile'),
    path('student/infos', views.communicates_list, name='s_infos'),
]

school/timetable/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django import forms

from .models import MyUser, Student, HourGroup, Teacher, Communicate
from django.contrib.auth.models import Group


class NewGroupForm(forms.ModelForm):
    class Meta:
        model = HourGroup
        fields = ['class_level', 'group_name', 'hour', 'week_day', 'student_limit', 'room']


class NewCommunicateForm(forms.ModelForm):
    destination_group = forms.ModelChoiceField(queryset=HourGroup.objects.all(), to_field_name='group_name')

    class Meta:
        model = Communicate
        fields = ['destination_group', 'communicate_title', 'communicate_text']


class ParticipantForm(forms.Form):
    student_name = forms.ModelChoiceField(queryset=MyUser.objects.filter(is_student=True), to_field_name='username')
    group_name = forms.ModelChoiceField(queryset=HourGroup.objects.all(), to_field_name='group_name')

    class Meta:
        model = HourGroup
        fields = ['student_name', 'group_name']


class StudentRegisterForm(UserCreationForm):
    YEAR_IN_SCHOOL_CHOICES = (
        ('I_SP', 'I SP'),
        ('II_SP', 'II SP'),
        ('III_SP', 'III SP'),
        ('IV_SP', 'IV SP'),
        ('V_SP', 'V SP'),
        ('VI_SP', 'VI SP'),
        ('VII_SP', 'VII SP'),
        ('VIII_SP', 'VIII SP'),
        ('III_GIM', 'III GIM')
    )
    student_class = forms.TypedChoiceField(choices=YEAR_IN_SCHOOL_CHOICES)
    first_name = forms.CharField(max_length=50)
    middle_name = forms.CharField(max_length=50, required=False, help_text='Not required')
    last_name = forms.CharField(max_length=50)

    class Meta(UserCreationForm.Meta):
        model = MyUser

    @transaction.atomic
    def save(self, **kwargs):
        user = super().save(commit=False)
        user.is_student = True
        user.first_name = self.cleaned_data.get('first_name')
        user.middle_name = self.cleaned_data.get('middle_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.save()
        student = Student.objects.create(user=user)
        student.my_class = self.cleaned_data.get('student_class')
        student.save()
        student_group = Group.objects.get(name='students')
        student_group.user_set.add(user)
        student_group.save()
        return user


class TeacherRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=50)
    middle_name = forms.CharField(max_length=50, required=False, help_text='Not required')
    last_name = forms.CharField(max_length=50)
    subject = forms.CharField(max_length=50, required=False, help_text='Not required')

    class Meta(UserCreationForm.Meta):
        model = MyUser

    @transaction.atomic
    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        user.is_student = False
        user.first_name = self.cleaned_data.get('first_name')
        user.middle_name = self.cleaned_data.get('middle_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.save()
        teacher = Teacher.objects.create(user=user)
        teacher.subject = self.cleaned_data.get('subject')
        teacher.save()
        # teacher.my_group = 'teachers'
        teachers_group = Group.objects.get(name='teachers')
        teachers_group.user_set.add(user)
        teachers_group.save()
        return user

school/timetable/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.generic import CreateView
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import Group
from django.contrib import messages
from datetime import timedelta, datetime
from django.contrib.auth import logout
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import login_required

from .models import MyUser, HourGroup, Teacher, Student
from .forms import StudentRegisterForm, TeacherRegisterForm, NewGroupForm, ParticipantForm, NewCommunicateForm


def is_teacher(user):
    return Group.objects.get(name='teachers') in user.groups.all()


def is_student(user):
    return Group.objects.get(name='students') in user.groups.all()

########################################

# Create your views here.


def logout_view(request):
    logout(request)
    return redirect('timetable:login')


@login_required
@user_passes_test(is_teacher)
def teacher_index(request):
    options = {
        ('teacher/register', 'Register new user'),
        ('teacher/groups', 'Add new group for my students'),
        ('teacher/new_participant', 'Add student to group'),
        ('teacher/remove_participant', 'Remove student from group'),
        ('teacher/my_groups', 'List of my groups'),
        ('teacher/communicate', 'Send new communicate'),
        ('teacher/my_profile', 'My personal data'),
    }
    context = {
        'user_type': "TEACHER",
        'options': options,
    }
    return render(request, 'timetable/profile_page.html', context)


@login_required
@user_passes_test(is_student)
def student_index(request):  # TODO
    options = {
        ('student/my_profile', 'My profile'),
        ('student/my_groups', 'My groups'),
        ('student/infos', 'Communicates'),
    }
    context = {
        'user_type': "STUDENT",
        'options': options,
    }
    return render(request, 'timetable/profile_page.html', context)


##############################################

@login_required
@user_passes_test(is_student)
def communicates_list(request):
    student = Student.objects.get(user=request.user)
    set_of_communicates = list()
    for g in student.my_course_groups.all():
        for c in g.communicate_set.all():
            set_of_communicates.append(c)
    set_of_communicates.sort(key=lambda x: x.pub_date, reverse=True)
    context = {
        'header_1': 'COMMUNICATES',
        'info': 'There are all communicates you have received',
        'elements': set_of_communicates
    }
    return render(request, 'timetable/communicates.html', context)


@login_required
@user_passes_test(is_student)
def student_groups(request):
    student = Student.objects.get(user=request.user)
    my_groups = student.my_course_groups
    context = {
        'header_1': 'MY GROUPS',
        'info': '',
        'elements': my_groups
    }
    return render(request, 'timetable/groups.html', context)


##############################


@login_required
def person_profile(request):
    try:
        Student.objects.get(user=request.user)
        student = Student.objects.get(user=request.user)
        context = {
            'user_type': 'student',
            'header_1': 'MY PERSONAL DATA',
            'person': student,
        }
    except Student.DoesNotExist:
            teacher = Teacher.objects.get(user=request.user)
            context = {
                'user_type': 'teacher',
                'header_1': 'MY PERSONAL DATA',
                'person': teacher
            }
    return render(request, 'timetable/info.html', context)


################################
@login_required
@user_passes_test(is_teacher)
def registration(request):
    options = {
        ('register/student/', 'New student'),
        ('register/teacher/', 'New teacher')
    }
    context = {
        'user_type': 'REGISTER',
        'options': options
    }
    return render(request, 'timetable/profile_page.html', context)


@login_required
@user_passes_test(is_teacher)
def new_group(request):
    context = {}
    if request.method == 'POST':
        form = NewGroupForm(request.POST)
        if form.is_valid():
            added_group = form.save(commit=False)
            added_group.teacher = Teacher.objects.get(user=request.user)
            added_group.teacher.subject = Teacher.objects.get(user=request.user).subject
            added_group.save()
            messages.success(request, 'Group successfully added!')
            return redirect('timetable:t_page')
        else:
            return HttpResponse("WHAT ARE YOU DOING?")
    else:
        form = NewGroupForm()
    context = {
        'name': "NEW CREATION",
        'form': form,
        'message': "Create new hour group"
    }
    return render(request, 'timetable/form.html', context)


@login_required
@user_passes_test(is_teacher)
def new_communicate(request):
    context = {}
    if request.method == 'POST':
        form = NewCommunicateForm(request.POST)
        if form.is_valid():
            added_communicate = form.save(commit=False)
            added_communicate.author = Teacher.objects.get(user=request.user)
            added_communicate.save()
            messages.success(request, 'Communicate successfully sent!')
            return redirect('timetable:t_page')
        else:
            return HttpResponse("WHAT ARE YOU DOING?")
    else:
        form = NewCommunicateForm()
    context = {
        'name': "NEW COMMUNICATE",
        'form': form,
        'message': "Create information communicate for your group"
    }
    return render(request, 'timetable/form.html', context)


@login_required
@user_passes_test(is_teacher)
def new_participant(request):
    context = {}
    if request.method == 'POST':
        form = ParticipantForm(request.POST)
        if form.is_valid():
            username = request.POST.get('student_name')
            student = Student.objects.get(user=MyUser.objects.get(username=username))
            hour_group = request.POST.get('group_name')
            chosen_group = HourGroup.objects.get(group_name=hour_group)
            if chosen_group.teacher.user == request.user:
                if chosen_group.participants_amount + 1 <= chosen_group.student_limit:
                    if check_if_possible(student, chosen_group):
                        student.my_course_groups.add(chosen_group)
                        student.save()
                        chosen_group.participants_amount += 1
                        chosen_group.save()
                        messages.success(request, 'Participant successfully added!')
                    else:
                        messages.success(request,
                                         'Student has already something during your course and cannot be added :( ')
                else:
                    messages.success(request, 'Too many participants!')
            else:
                messages.error(request, 'It is not your group! Please ask your colleague!')
            return redirect('timetable:t_page')
        else:
            return HttpResponse("WHAT ARE YOU DOING?")
    else:
        form = ParticipantForm()
    context = {
        'name': "NEW PARTICIPANT",
        'info': "Choose correct group",
        'form': form,
    }
    return render(request, 'timetable/form.html', context)


@login_required
@user_passes_test(is_teacher)
def remove_participant(request):
    context = {}
    if request.method == 'POST':
        form = ParticipantForm(request.POST)
        if form.is_valid():
            username = request.POST.get('student_name')
            student = Student.objects.get(user=MyUser.objects.get(username=username))
            hour_group = request.POST.get('group_name')
            chosen_group = HourGroup.objects.get(group_name=hour_group)
            if chosen_group.teacher.user == request.user:
                if chosen_group in student.my_course_groups.all():
                    student.my_course_groups.remove(chosen_group)
                    student.save()
                    chosen_group.participants_amount -= 1
                    chosen_group.save()
                    messages.success(request, 'Participant successfully removed!')
                else:
                    messages.error(request, 'Not in group!')
            else:
                messages.error(request, 'It is not your group!!')
            return redirect('timetable:t_page')
        else:
            return HttpResponse("WHAT ARE YOU DOING?")
    else:
        form = ParticipantForm()
    context = {
        'name': "REMOVE PARTICIPANT",
        'info': "Choose participant to remove",
        'form': form,
    }
    return render(request, 'timetable/form.html', context)


@login_required
@user_passes_test(is_teacher)
def teacher_groups(request):
    teacher = Teacher.objects.get(user=request.user)
    list_of_groups = HourGroup.objects.filter(teacher=teacher)
    context = {
        'header_1': 'MY GROUPS',
        'elements': list_of_groups,
        'param_1': 'Group names',
        'info': 'Click the group name to see details',
    }
    return render(request, 'timetable/hiperlist.html', context)


@login_required
@user_passes_test(is_teacher)
def group_participants(request, id):
    hour_group = HourGroup.objects.get(id=id)
    list_of_students = set()
    for s in Student.objects.all():
        if hour_group in s.my_course_groups.all():
            list_of_students.add(s.user)
    context = {
        'header_1': 'PARTICIPANTS OF THIS GROUP',
        'elements': list_of_students,
        'param_1': 'First name',
        'param_2': 'Middle name',
        'param_3': 'Last name',
        'group': hour_group,
    }
    return render(request, 'timetable/participants.html', context)


#################################

def home_page(request):
    user = request.user
    teachers = Group.objects.get(name="teachers").user_set.all()
    if user in teachers:

school/timetable/templates/timetable/communicates.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>

<div class="container">
    <div class="jumbotron">
        <h1>{{ header_1 }}</h1>

        <p>{{ info }} </p>
    </div>


    {% for e in elements %}
    <div class="container">
        <ul class="list-group">
            <li class="list-group-item"><strong>{{ e.communicate_title }} --- {{ e.destination_group }} </strong> </li>
            <li class="list-group-item"> {{ e.communicate_text }}</li>
            <li class="list-group-item"> {{ e.pub_date}} --- {{ e.author }}</li>
        </ul>
    </div>
    {% endfor %}



    <p><a href="{% url 'timetable:s_page' %}"> Back </a></p>
    <p><a href="{% url 'timetable:logout' %}"> Logout </a></p>
    <p></p>
    <p></p>
    <p></p>

</div>

</body>
</html>

school/timetable/templates/timetable/form.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>

<div class="container">
    <div class="jumbotron">

    <h1> {{ name }} PAGE</h1>
    </div>
    <div class="container">
        <h2> {{ info }} </h2>

        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {{ form.as_p }}

            <div class="container">
            <input type="submit" value="Submit"/>
            </div>

        </form>
    </div>
    <p></p>
</div>

</body>
</html>

school/timetable/templates/timetable/groups.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>

<div class="container">
    <div class="jumbotron">

    <h1>{{ header_1 }}</h1>
    </div>

    <div class="container">



    <p>{{ info }} </p>
         </div>

    <div class="container">


    <ul>

        {% for e in elements.all %}
        <li>{{ e.group_name }} -- {{ e.week_day }} -- {{ e.hour }} -- {{ e.room }} -- {{ e.teacher.user.full_name}}</li>
        {% endfor %}
    </ul>

    </div>
    <p><a href="{% url 'timetable:s_page' %}"> Back </a></p>
    <p><a href="{% url 'timetable:logout' %}"> Logout </a></p>
    <p></p>
    <p></p>
    <p></p>
</div>

</body>
</html>

school/timetable/templates/timetable/hiperlist.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>

<div class="container">
    <div class="jumbotron">

        <h1>{{ header_1 }}</h1>
        <h2>{{ param_1 }} </h2>

    </div>
    <div class="container">

        <p>{{ info }} </p>
        <ul>

            {% for e in elements.all %}
            <li><a href="{% url 'timetable:detail' e.id %}">{{ e.group_name }} </a></li>
            {% endfor %}
        </ul>
    </div>

    <p><a href="{% url 'timetable:t_page' %}"> Back </a></p>
    <p><a href="{% url 'timetable:logout' %}"> Logout </a></p>


    <p></p>
    <p></p>
    <p></p>
</div>

</body>
</html>

school/timetable/templates/timetable/info.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>

<div class="container">
    <div class="jumbotron">

    <h1>{{ header_1 }}</h1>

    <h2> {{ person.full_name }} </h2>
    </div>

    <div class="container">


    <ul>
        <p> {{ user_type }}'s last name: {{ person.user.last_name }} </p>
        <p> {{ user_type }}'s first name: {{ person.user.first_name }} </p>
        <p> {{ user_type }}'s middle name: {{ person.user.middle_name }} </p>
        {% if user_type == 'student' %}
        <p> {{ user_type }}'s class: {{ person.my_class }} </p>
        {% else %}
        <p> {{ user_type }}'s subject: {{ person.subject }} </p>
        {% endif %}
    </ul>

    </div>

    {% if user_type == 'student' %}
    <p><a href="{% url 'timetable:s_page' %}"> Back </a></p>
    {% else %}
    <p><a href="{% url 'timetable:t_page' %}"> Back </a></p>
    {% endif %}

    <p><a href="{% url 'timetable:logout' %}"> Logout </a></p>


    <p></p>
    <p></p>
    <p></p>
</div>

</body>
</html>

school/timetable/templates/timetable/login.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>

<div class="container">
    <div class="jumbotron">
        <h1> WELCOME TO THE SYSTEM!</h1>
    </div>

    <div class="container">
        {% block content %}
        <h2>Login</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
        {% endblock %}
        <p></p>
        <p></p>
        <p></p>
    </div>

</div>

</body>
</html>

school/timetable/templates/timetable/participants.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>

<div class="container">
    <div class="jumbotron">

        <h1>{{ header_1 }}</h1>

        <h2> {{ group.group_name }} </h2>
        <h3> -- {{ group.week_day }} -- {{ group.hour }} -- {{ group.participants_amount }}/{{ group.student_limit }} -- {{ group.room }} </h3>

    </div>
    <div class="container">
        <p>Students:  </p>
        <ul>
            {% for e in elements %}
            <li>{{ e.first_name }} {{ e.middle_name }} {{ e.last_name }}</li>
            {% endfor %}
        </ul>

    </div>
    <p><a href="{% url 'timetable:t_page' %}"> Back </a></p>
    <p><a href="{% url 'timetable:logout' %}"> Logout </a></p>


    <p></p>
    <p></p>
    <p></p>
</div>
</body>
</html>

school/timetable/templates/timetable/profile_page.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<body>

<div class="container">
    <div class="jumbotron">

        <h1> {{ user_type }} PAGE!</h1>

        {% if user.is_authenticated %}
        <h2> Welcome {{ user.username }}!!!</h2>
        {% endif %}

    </div>

    <div class="container">

        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
    </div>

    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <p><strong>{{ message }}</strong></p>
        {% endfor %}
        {% endif %}
    </div>
    <div class="container">
        <p> Chose what to do: </p>
    </div>


    <div class="container">

        <ul>
            {% for option in options %}
            <li><a href="{{ option.0 }}">{{ option.1 }} </a></li>
            {% endfor %}

            {% if user_type == "STUDENT" %}
            <li><a href="{% url 'timetable:s_page' %}"> Back </a></li>
            {% else %}
            <li><a href="{% url 'timetable:t_page' %}"> Back </a></li>
            {% endif %}
            <li><a href="{% url 'timetable:logout' %}"> Logout </a></li>

        </ul>

    </div>
</div>
</body>
</html>